package dev.flammky.valorantcompanion.pvp.error

object PVPModuleErrorCodes {

    val AUTH_TOKEN_UNAVAILABLE = 1901

    val GEOLOCATION_UNAVAILABLE = 1902

    val UNEXPECTED_REMOTE_RESPONSE = 1911

    val UNHANDLED_REMOTE_EXCEPTION = 1998

    val UNHANDLED_EXCEPTION = 1999
}